config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , except: [:index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
    validates :name , length: { maximum: 20 } , presence: true
    validates :body , length: { minumum: 2, maximum: 30 } , presence: true
    validates :age , numericality: { only_integer:true, greater_than_or_equal_to:0, less_than_or_equal_to:200 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]
  
  def edit
  end

  def update
    if @message.update(message_params)
      redirect_to root_path , notice: 'Completed edit message'
      
    else
      render 'edit'
    end
  end
  
  def destroy
    @message.destroy
    redirect_to root_path, notice: 'Deleted the message.'
  end
  
  def index
    @messages = Message.all
    @message = Message.new
  end


  def create
      @message = Message.new(message_params)
    if @message.save
      redirect_to root_path , notice: "Saved message"
    else
      @messages = Message.all
      flash.now[:alert] = "Sorry, failed to save the message"
      render 'index'
    end
  end
 
  private
  
  def set_message
    @message = Message.find(params[:id])
  end
  
  def message_params
    params.require(:message).permit(:name, :body, :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <style>
    body {
      min-height: 1200px;
    }
    
    .navbar {
      background-color: #3498db;
    }
    
    .navbar-brand {
      color: black;
      font-size: 30px;
      margin-top: 10px;
      padding-bottom: 40px;
    }
    
    .panel-heading {
      text-align: center;
      font-size: 20px;
      color: blue;
    }
    

  </style>
</head>
<body>
    <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Message Board</a>
      </div>
    </div>
  </nav>
  <div class="container">
    <% if notice %>
      <div class="alert alert-info">
        <%= notice %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(Message.new, html: {class: "form-horizontal"}) do |f| %> 
  <% if @message.errors.present? %>
    <div class="alert alert-danger">
        <%= alert %>
        <ul>
            <% @message.errors.full_messages.each do |full_message| %>
            <li>
                <%= full_message %>
            </li>
            <% end %>
        </ul>
    </div>
    <% end %>
  <div class="form-group">
     <%= f.label :name, :id => "name-label", :class => "col-sm-1 control-label", style: "font-size:20px; " %>
     <div class="col-sm-11">
        <%= f.text_field :name, :class => "form-control" %>
     </div>
  </div>
  <br>
  <div class="form-group">
     <%= f.label :name, "Content", :class => "col-sm-1 control-label", style: "font-size:20px; " %>
     <div class="col-sm-11">
        <%= f.text_area :body, class: "form-control" %>
     </div>
  </div>
  
<<<<<<< HEAD
  <div class="form-group" style="inline-block">
=======
  <div class="form-group">
>>>>>>> challenge2
     <%= f.label :age, "Age", :class => "col-sm-1 control-label", style: "font-size:20px;" %>
     <div class="col-sm-5">
         <%= f.number_field :age, :class => "form-control" %>
     </div>
     <div class="col-sm-6">
        <%= f.submit "Send", class: "btn-sm btn-primary btn-block", style: "font-size:15px;" %>
     </div>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Edit message</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<div class="panel panel-default">
   <div class="panel-heading">
      Message List
   </div>
   
   <div class="panel-body">
      <% @messages.each do |message| %>
        <span class="label label-info" style="font-size: 12px; background-color: #3498db;"><%= message.name %></span>
        <br>
        <%= message.body %>
        (<%= link_to "edit" , edit_message_path(message) %>)
        (<%= link_to "destroy" , message , method: :delete, data: { confirm: 'Do you want delete this message?' } %>)
        <br>
      <% end %>
   </div>
</div>

<<<<<<< HEAD
<%= render 'form' %>
=======
<%= render 'form' %>
  
  
>>>>>>> challenge2